# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e54be7708e3ba363b84a5cb46dc2506843b2e8d5187a7480476afc7e27d916612ca7cb419fd920e1dbee8284c2a88d67596d3b37226b4403f54f209979b67d79

test:
  secret_key_base: 7a05bbed788d978cbfdbe0752702bae1afa8d8375cba466d1b03c7bd52b95bc4f352674a6fa1a7b83da71f9d3519e8f2a91c7a2ee0a4722fa5963f44af571e88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
